### ISSUE TITLE
Images are wrong size on Chrome for Retina Displays

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/srtracker#59]
@2x images are not being sized correctly for the logo in the header and the links in the footer on retina displays in Chrome:
![Screen Shot 2013-03-04 at 11 32 23 PM](https://f.cloud.github.com/assets/74178/220322/fb6b0096-8566-11e2-936b-5301cfc52bd4.png)
![Screen Shot 2013-03-04 at 11 32 50 PM](https://f.cloud.github.com/assets/74178/220325/070b9e7e-8567-11e2-8cb3-aa87011460d9.png)

Looks like this is being caused by specifying `background` instead of `background-image` in the CSS:

``` css
.landing header {
  background: url("../img/311_service_tracker_logo_big_x2.png");
}
```

In Safari, the shorthand property does not override `background-size`, but in Chrome it does, so we're losing the size information when we do this.
